### ISSUE TITLE
Tessalation points 

### ISSUE THREAD

**Issue by tcrakshi** [evereux/pycatia#42]
Is it pycatia have tessalation point command?

**Comment by evereux** [comment]
github issues are normally a place to report issues with a script that isn't
working as expected or issues with pycatia itself. Whilst I'm happy to support
new users to get them up and running I can't continue to provide technical 
support for questions that ask "Can pycatia do x?". Or simply "How do I?".
pycatia is currently, free open source software that can potentially save
companies many man hours and does not come with technical support.


If it's documented in the CAA.chm file there is a good chance it is or could 
be. Find what the class name of the method you want to use and search the 
`API <https://pycatia.readthedocs.io/en/latest/api_index.html>`_ for it. Or, do
the same with the source code in your IDE.


Using the class methods in pycatia will be very similar to how one would do so
in CATScript / VBScript.


If your script isn't working please post that script here, properly formatted,
so I can run it and we can find where the problem lies. Please strip the script
down to the bare essentials before you do so.


If you would like technical support for pycatia please contact me 
evereux@gmail.com, from a business address, and we can discuss contracting my
technical support for your company.

I'm closing this ticket. If some code is provided please feel free to re-open.
